version: '3.8'

# Services
services:

  # PHP Service
  workspace:
    build:
      context: ./docker/php
    working_dir: /var/www/php
    volumes:
        - ./src:/var/www/php
        - ./.docker/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro


